version: '3'

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - main
  web:
    build: .
    env_file: .env
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000 # only use in dev
    # command: gunicorn --env DJANGO_SETTINGS_MODULE=ausglamr.settings ausglamr.wsgi --workers=10 --threads=4 -b 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - main
    ports:
      - "8282:8000"
volumes:
  pgdata:
networks:
  main: